### ISSUE TITLE
Use pipes for SE "big mining drill"

### ISSUE THREAD

**Issue by ChucklesTheBeard** [ChucklesTheBeard/OutpostPlanner#3]
https://github.com/ChucklesTheBeard/OutpostPlanner/issues/2#issuecomment-1016979344

>sadly it wont understand that it need pipes tho - is that something that you can fix? The tier 3 miner is the "big mining drill"

**Comment by CurlyFlow** [comment]
https://we.tl/t-XjLGhTVpze

**Comment by ChucklesTheBeard** [comment]
Thank you, I'll check it out tomorrow.

**Comment by ChucklesTheBeard** [comment]
I've got this *mostly* fixed to work on arbitrarily large (square) miners, but I haven't been able to figure out where this pipe is placed to fix it.
![screenshot with red circle](https://user-images.githubusercontent.com/12536545/150619875-b7d4766b-a9e8-41d3-9ef4-0b6f9513ca09.png)

**Comment by ChucklesTheBeard** [comment]
Fixed in next version of PlannerCore for 1.1
